name: CI
on: [push]
permissions:
  contents: read
  pages: read
  id-token: write
  checks: write
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}